services:
  db:
    image: postgres:16
    container_name: sportspub-db
    environment:
      POSTGRES_DB: sportspub_db
      POSTGRES_USER: sportspub
      POSTGRES_PASSWORD: sportspub
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
