-- 경기 일정 알림 저장 테이블 (#116)
-- 홈팀·원정팀 ID는 match_id를 통해 조회하며 notifications에 중복 저장하지 않는다.

CREATE TABLE notifications (
    notification_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           BIGINT        NOT NULL,
    match_id          BIGINT        NOT NULL,
    type              VARCHAR(30)   NOT NULL,
    title             VARCHAR(100)  NOT NULL,
    content           TEXT          NOT NULL,
    is_read           BOOLEAN       NOT NULL DEFAULT FALSE,
    deep_link_type    VARCHAR(30)   NOT NULL,
    created_at        TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_notifications_user
        FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
    CONSTRAINT fk_notifications_match
        FOREIGN KEY (match_id) REFERENCES matches(match_id) ON DELETE CASCADE,
    CONSTRAINT ck_notifications_type
        CHECK (type IN ('GAME_REMINDER')),
    CONSTRAINT ck_notifications_deep_link_type
        CHECK (deep_link_type IN ('TOMORROW_GAME', 'TODAY_PUBS', 'NEARBY_PUBS'))
);

CREATE INDEX idx_notifications_user_created
    ON notifications(user_id, created_at DESC);
