-- ============================================================================
-- V1 baseline — 야구펍 서비스 MVP ERD v1.2 (15테이블 일괄)
-- 기준 문서: docs/ERD_v1.md (v1.2)
-- 컨벤션: snake_case, BIGINT IDENTITY, ENUM은 VARCHAR + CHECK, KST TIMESTAMP
-- 마이그레이션 순서: teams → users → refresh_tokens → withdrawal_reasons
--                  → user_favorite_teams → matches → pubs → pub_images
--                  → pub_supported_teams → menus → pub_facilities
--                  → pub_business_hours → favorites → reports → report_images
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1) teams (구단 마스터) — sport_type 선반영 (D3)
-- ----------------------------------------------------------------------------
CREATE TABLE teams (
    team_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sport_type    VARCHAR(20)  NOT NULL DEFAULT 'KBO',
    name          VARCHAR(30)  NOT NULL,
    short_name    VARCHAR(10)  NOT NULL,
    home_stadium  VARCHAR(50),
    created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_teams_sport_name  UNIQUE (sport_type, name),
    CONSTRAINT uk_teams_sport_short UNIQUE (sport_type, short_name),
    CONSTRAINT ck_teams_sport_type
        CHECK (sport_type IN ('KBO', 'KBL', 'KLEAGUE', 'KOVO', 'OTHER'))
);

-- ----------------------------------------------------------------------------
-- 2) users (회원)
-- ----------------------------------------------------------------------------
CREATE TABLE users (
    user_id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    oauth_provider        VARCHAR(20)  NOT NULL,
    oauth_id              VARCHAR(100) NOT NULL,
    nickname              VARCHAR(20),
    role                  VARCHAR(20)  NOT NULL DEFAULT 'FAN',
    onboarding_completed  BOOLEAN      NOT NULL DEFAULT FALSE,
    deleted_at            TIMESTAMP,
    created_at            TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at            TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_users_oauth UNIQUE (oauth_provider, oauth_id),
    CONSTRAINT ck_users_oauth_provider
        CHECK (oauth_provider IN ('KAKAO', 'NAVER')),
    CONSTRAINT ck_users_role
        CHECK (role IN ('FAN', 'OWNER', 'ADMIN')),
    CONSTRAINT ck_users_nickname
        CHECK (nickname IS NULL OR (
            CHAR_LENGTH(nickname) BETWEEN 2 AND 20
            AND nickname ~ '^[가-힣a-zA-Z0-9]+$'
        ))
);

-- ----------------------------------------------------------------------------
-- 3) refresh_tokens (1인 1토큰)
-- ----------------------------------------------------------------------------
CREATE TABLE refresh_tokens (
    refresh_token_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           BIGINT     NOT NULL,
    token_hash        VARCHAR(64) NOT NULL,
    expires_at        TIMESTAMP  NOT NULL,
    created_at        TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_refresh_tokens_user UNIQUE (user_id),
    CONSTRAINT fk_refresh_tokens_user
        FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);

CREATE INDEX idx_refresh_tokens_expires ON refresh_tokens(expires_at);

-- ----------------------------------------------------------------------------
-- 4) withdrawal_reasons (탈퇴 사유, append-only)
-- ----------------------------------------------------------------------------
CREATE TABLE withdrawal_reasons (
    withdrawal_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        BIGINT       NOT NULL,
    reason_code    VARCHAR(30)  NOT NULL,
    detail         TEXT,
    created_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_withdrawal_reasons_user
        FOREIGN KEY (user_id) REFERENCES users(user_id),
    CONSTRAINT ck_withdrawal_reasons_code
        CHECK (reason_code IN (
            'NO_USE', 'INSUFFICIENT_DATA', 'INACCURATE_DATA', 'APP_ISSUE', 'OTHER'
        ))
);

CREATE INDEX idx_withdrawal_reasons_code ON withdrawal_reasons(reason_code);

-- ----------------------------------------------------------------------------
-- 5) user_favorite_teams (선호 구단 M:N, 최대 3개 — 앱 레벨 검증)
-- ----------------------------------------------------------------------------
CREATE TABLE user_favorite_teams (
    user_favorite_team_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                BIGINT     NOT NULL,
    team_id                BIGINT     NOT NULL,
    created_at             TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_user_favorite_teams_user_team UNIQUE (user_id, team_id),
    CONSTRAINT fk_user_favorite_teams_user
        FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
    CONSTRAINT fk_user_favorite_teams_team
        FOREIGN KEY (team_id) REFERENCES teams(team_id)
);

CREATE INDEX idx_user_favorite_teams_team ON user_favorite_teams(team_id);

-- ----------------------------------------------------------------------------
-- 6) matches (경기) — 크롤러 직접 적재 (v1.2)
-- ----------------------------------------------------------------------------
CREATE TABLE matches (
    match_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sport_type     VARCHAR(20)  NOT NULL DEFAULT 'KBO',
    match_date     DATE         NOT NULL,
    start_time     TIME,
    home_team_id   BIGINT       NOT NULL,
    away_team_id   BIGINT       NOT NULL,
    stadium        VARCHAR(50),
    home_score     INTEGER,
    away_score     INTEGER,
    status         VARCHAR(20)  NOT NULL,
    created_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_matches_natural
        UNIQUE (sport_type, match_date, home_team_id, away_team_id),
    CONSTRAINT fk_matches_home_team
        FOREIGN KEY (home_team_id) REFERENCES teams(team_id),
    CONSTRAINT fk_matches_away_team
        FOREIGN KEY (away_team_id) REFERENCES teams(team_id),
    CONSTRAINT ck_matches_teams_diff
        CHECK (home_team_id <> away_team_id),
    CONSTRAINT ck_matches_status
        CHECK (status IN ('SCHEDULED', 'LIVE', 'FINISHED', 'CANCELED', 'POSTPONED')),
    CONSTRAINT ck_matches_sport_type
        CHECK (sport_type IN ('KBO', 'KBL', 'KLEAGUE', 'KOVO', 'OTHER'))
);

CREATE INDEX idx_matches_sport_date      ON matches(sport_type, match_date);
CREATE INDEX idx_matches_home_team_date  ON matches(home_team_id, match_date);
CREATE INDEX idx_matches_away_team_date  ON matches(away_team_id, match_date);

-- ----------------------------------------------------------------------------
-- 7) pubs (스포츠 펍)
-- ----------------------------------------------------------------------------
CREATE TABLE pubs (
    pub_id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                  VARCHAR(100)  NOT NULL,
    address               VARCHAR(200)  NOT NULL,
    region                VARCHAR(30)   NOT NULL,
    latitude              DECIMAL(10,7) NOT NULL,
    longitude             DECIMAL(10,7) NOT NULL,
    phone                 VARCHAR(20),
    status                VARCHAR(20)   NOT NULL DEFAULT 'OPEN',
    capacity_range        VARCHAR(20),
    group_seat_max_people INTEGER,
    favorite_count        INTEGER       NOT NULL DEFAULT 0,
    description           TEXT,
    deleted_at            TIMESTAMP,
    created_at            TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at            TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_pubs_latitude       CHECK (latitude  BETWEEN 33 AND 39),
    CONSTRAINT ck_pubs_longitude      CHECK (longitude BETWEEN 124 AND 132),
    CONSTRAINT ck_pubs_status
        CHECK (status IN ('OPEN', 'CLOSED', 'TEMP_CLOSED')),
    CONSTRAINT ck_pubs_capacity_range
        CHECK (capacity_range IS NULL OR capacity_range IN (
            'UNDER_20', 'R_20_50', 'R_50_100', 'OVER_100'
        )),
    CONSTRAINT ck_pubs_group_seat
        CHECK (group_seat_max_people IS NULL OR group_seat_max_people >= 0),
    CONSTRAINT ck_pubs_favorite_count CHECK (favorite_count >= 0)
);

CREATE INDEX idx_pubs_bbox            ON pubs(latitude, longitude);
CREATE INDEX idx_pubs_region_status   ON pubs(region, status);
CREATE INDEX idx_pubs_favorite_count  ON pubs(favorite_count DESC);

-- ----------------------------------------------------------------------------
-- 8) pub_images
-- ----------------------------------------------------------------------------
CREATE TABLE pub_images (
    image_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pub_id         BIGINT        NOT NULL,
    image_url      VARCHAR(500)  NOT NULL,
    display_order  SMALLINT      NOT NULL DEFAULT 0,
    created_at     TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_pub_images_pub
        FOREIGN KEY (pub_id) REFERENCES pubs(pub_id) ON DELETE CASCADE
);

CREATE INDEX idx_pub_images_pub_order ON pub_images(pub_id, display_order);

-- ----------------------------------------------------------------------------
-- 9) pub_supported_teams (펍 ↔ 상영 구단 M:N)
-- ----------------------------------------------------------------------------
CREATE TABLE pub_supported_teams (
    pub_id   BIGINT NOT NULL,
    team_id  BIGINT NOT NULL,
    PRIMARY KEY (pub_id, team_id),
    CONSTRAINT fk_pub_supported_teams_pub
        FOREIGN KEY (pub_id) REFERENCES pubs(pub_id) ON DELETE CASCADE,
    CONSTRAINT fk_pub_supported_teams_team
        FOREIGN KEY (team_id) REFERENCES teams(team_id)
);

CREATE INDEX idx_pub_supported_teams_team ON pub_supported_teams(team_id);

-- ----------------------------------------------------------------------------
-- 10) menus
-- ----------------------------------------------------------------------------
CREATE TABLE menus (
    menu_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pub_id         BIGINT       NOT NULL,
    name           VARCHAR(50)  NOT NULL,
    category       VARCHAR(20)  NOT NULL,
    price          INTEGER,
    display_order  SMALLINT     NOT NULL DEFAULT 0,
    created_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_menus_pub
        FOREIGN KEY (pub_id) REFERENCES pubs(pub_id) ON DELETE CASCADE,
    CONSTRAINT ck_menus_category
        CHECK (category IN ('FOOD', 'DRINK', 'SET')),
    CONSTRAINT ck_menus_price
        CHECK (price IS NULL OR price >= 0)
);

CREATE INDEX idx_menus_pub_order    ON menus(pub_id, display_order);
CREATE INDEX idx_menus_pub_category ON menus(pub_id, category);

-- ----------------------------------------------------------------------------
-- 11) pub_facilities (v1.2 단순화: facility_code VARCHAR + CHECK, 마스터 없음)
-- ----------------------------------------------------------------------------
CREATE TABLE pub_facilities (
    pub_id         BIGINT       NOT NULL,
    facility_code  VARCHAR(30)  NOT NULL,
    created_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (pub_id, facility_code),
    CONSTRAINT fk_pub_facilities_pub
        FOREIGN KEY (pub_id) REFERENCES pubs(pub_id) ON DELETE CASCADE,
    CONSTRAINT ck_pub_facilities_code
        CHECK (facility_code IN (
            'BIG_SCREEN', 'PROJECTOR', 'GROUP_SEAT', 'PARKING', 'RESERVATION',
            'KIDS_ZONE', 'PET_FRIENDLY', 'NO_SMOKING', 'LATE_NIGHT', 'WIFI'
        ))
);

CREATE INDEX idx_pub_facilities_code ON pub_facilities(facility_code);

-- ----------------------------------------------------------------------------
-- 12) pub_business_hours (요일별 영업시간, ISO-8601 1=월 ~ 7=일)
-- ----------------------------------------------------------------------------
CREATE TABLE pub_business_hours (
    pub_id       BIGINT    NOT NULL,
    day_of_week  SMALLINT  NOT NULL,
    open_time    TIME,
    close_time   TIME,
    is_closed    BOOLEAN   NOT NULL DEFAULT FALSE,
    PRIMARY KEY (pub_id, day_of_week),
    CONSTRAINT fk_pub_business_hours_pub
        FOREIGN KEY (pub_id) REFERENCES pubs(pub_id) ON DELETE CASCADE,
    CONSTRAINT ck_pub_business_hours_day
        CHECK (day_of_week BETWEEN 1 AND 7),
    CONSTRAINT ck_pub_business_hours_closed
        CHECK (
            (is_closed = TRUE  AND open_time IS NULL AND close_time IS NULL)
         OR (is_closed = FALSE)
        )
);

-- ----------------------------------------------------------------------------
-- 13) favorites (즐겨찾기)
-- ----------------------------------------------------------------------------
CREATE TABLE favorites (
    favorite_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT     NOT NULL,
    pub_id       BIGINT     NOT NULL,
    created_at   TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_favorites_user_pub UNIQUE (user_id, pub_id),
    CONSTRAINT fk_favorites_user
        FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
    CONSTRAINT fk_favorites_pub
        FOREIGN KEY (pub_id) REFERENCES pubs(pub_id) ON DELETE CASCADE
);

CREATE INDEX idx_favorites_user_created ON favorites(user_id, created_at DESC);

-- ----------------------------------------------------------------------------
-- 14) reports (제보) — subcategory + IN_REVIEW (D8)
-- ----------------------------------------------------------------------------
CREATE TABLE reports (
    report_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT       NOT NULL,
    pub_id       BIGINT,
    category     VARCHAR(30)  NOT NULL,
    subcategory  VARCHAR(30),
    content      TEXT         NOT NULL,
    status       VARCHAR(20)  NOT NULL DEFAULT 'PENDING',
    created_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_reports_user
        FOREIGN KEY (user_id) REFERENCES users(user_id),
    CONSTRAINT fk_reports_pub
        FOREIGN KEY (pub_id) REFERENCES pubs(pub_id) ON DELETE SET NULL,
    CONSTRAINT ck_reports_category
        CHECK (category IN ('PUB_INFO_ERROR', 'MISSING_PUB', 'GENERAL', 'OTHER')),
    CONSTRAINT ck_reports_status
        CHECK (status IN ('PENDING', 'IN_REVIEW', 'RESOLVED', 'REJECTED'))
);

CREATE INDEX idx_reports_status_created   ON reports(status, created_at DESC);
CREATE INDEX idx_reports_pub              ON reports(pub_id) WHERE pub_id IS NOT NULL;
CREATE INDEX idx_reports_category_status  ON reports(category, status);

-- ----------------------------------------------------------------------------
-- 15) report_images (append-only)
-- ----------------------------------------------------------------------------
CREATE TABLE report_images (
    image_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_id   BIGINT        NOT NULL,
    image_url   VARCHAR(500)  NOT NULL,
    created_at  TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_report_images_report
        FOREIGN KEY (report_id) REFERENCES reports(report_id) ON DELETE CASCADE
);
