plugins {
    id 'org.springframework.boot'
}

bootJar {
    archiveFileName = 'sportspub-crawler.jar'
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'

    implementation 'com.microsoft.playwright:playwright:1.45.0'

    runtimeOnly 'org.postgresql:postgresql'
}
